### ISSUE TITLE
Disappointed about the new version of Logi Circle component in HA

### ISSUE THREAD

**Issue by Obicom** [evanjd/hass-logi-circle#3]
Hi, I am really disappointed about the new version of Logi Circle component in HA with version 0.92.0 (breaking change). I am not able to generate a redirect link to request an api key. I am not willing to open my HA from outside with a HTTPS connection. Does this mean I am no longer able to use my Logi Circle cameras in HA? BR Dirk

**Comment by evanjd** [comment]
In future, please raise issues over at https://github.com/home-assistant/home-assistant repo if your problem relates to the hass integration.

> I am not willing to open my HA from outside with a HTTPS connection. Does this mean I am no longer able to use my Logi Circle cameras in HA?

There is no requirement for HA to be exposed from outside your network. The only requirement is that the hostname is valid and is one you own/control.

Let's say you specify your redirect uri as 'https://obicoms-domain.com`. You could either:
a) Set a static route on your local network that routes `obicoms-domain.com` to your local HA instance. Or reverse proxy or whatever.
b) Have the redirect 404, then change the URL in the address bar yourself to your local HA instance.

You can also just use override the `logi_circle` integration with an old version by adding that in the custom_components folder, keeping in mind that it could break at any time.

> I am really disappointed

I hope you realise that I do this for free with my spare time. The old version of the integration relied on a private API I reverse engineered from their web app - this can break at _any_ time if Logitech change anything about their web app. I do not have the capacity to rapidly respond to breaking API changes, so switching to their public API (which is documented, sanctioned and supported by Logitech) is the best long term decision for the stability of the integration.

**Comment by Obicom** [comment]
Thank you for your quick answer. From my IT knowledge ist this what you described an access from outside to my internal network .. I redirect an access from outside to my internal HA URL with an static route via my router. Logitech will deliver the api key only if they can check and access the redirected link.

Let's say you specify your redirect uri as 'https://obicoms-domain.com`. You could either:
a) Set a static route on your local network that routes obicoms-domain.com to your local HA instance. Or reverse proxy or whatever.

**Comment by evanjd** [comment]
> Logitech will deliver the api key only if they can check and access the redirected link.

Is that they were said? Do you mind quoting their advice here?

I don't have my HA instance exposed externally, and they let me register a URL that has a blank page (ie. it's a real host that I control, it just serves a static page) which I redirect locally to my HA instance. But it's possible they changed their requirements since I requested this access.

**Comment by Obicom** [comment]
This is what I got from Logitech:

![image](https://user-images.githubusercontent.com/25134482/56798188-96cb8400-6816-11e9-8529-ed59e64cbe47.png)

 Maybe we have a misunderstanding what is really needed and what is meant with "Redirect URL". Currently I have no https access to HA. From my point of view it is not necessary in my local network. If I would switch to https I got this ugly message "No secure site" in regards to an certificate not proofen by an valid root certificate. 

For what exactly need Logitech this redirect URL? What I the easiest and secure way to fulfill the needed requirements for an https redirect URL?

**Comment by evanjd** [comment]
OK, so I guess there needs to be _something_ at the redirect URI. It shouldn't need to be HA, just a static page or something is hopefully sufficient (as it was for me). When you get redirected to that page, you can then redirect back to your local HA instance (static route, JS redirection, modifying the URL by hand, etc).

I'll e-mail Logitech and confirm that. I'll reply here when I hear back.

**Comment by evanjd** [comment]
Got a response from Logitech. The requirements for the redirect URI are:

1. It must be HTTPS
2. The certificates must be issued by a trusted CA (trusted by normal browsers)
3. At the time they submit the request to us, they need to prove they have exclusive control over the fully qualified domain name they are requesting. Normally they verify this by testing the redirect URL to make sure it responds with a standard HA 404, but any message that demonstrates control of the domain is sufficient (incl. a static page on a free host, like netlify).
4. This means the domain name must resolve and connect when we test it (aka public facing).
5. No .local domains are allowed as they are not exclusively controlled by a single user. (Can allow for domain / credential hijacking of OAuth2 credentials)

I'm closing and disabling issues on this repo. Feel free to reopen this on home-assistant's repo if you want to continue the discussion. In the mean time, I will submit a PR for home-assistant to better articulate these requirements on the official docs.

**Comment by evanjd** [comment]
@Obicom The [official HA docs have been updated](https://www.home-assistant.io/components/logi_circle/#requesting-api-access) with clearer requirements about what redirect URIs Logitech expect.

I've also published a custom component that allows people stuck without an API key to upgrade to HA 0.92, see here: https://github.com/evanjd/hass-logi-circle/tree/legacy
