### ISSUE TITLE
Logi-circle-legacy Errors after updating to 0.94.0

### ISSUE THREAD

**Issue by nenadmilano** [evanjd/hass-logi-circle#4]
After updating to Home Assistant 0.94.0 i get the following error messages:
![image](https://user-images.githubusercontent.com/32328649/59053444-c055e180-8891-11e9-95ef-7874d5084daa.png)
![image](https://user-images.githubusercontent.com/32328649/59053490-dbc0ec80-8891-11e9-9cac-ebbc03e4bf7c.png)

**Comment by nenadmilano** [comment]
nevermind, it seems that the issue was related to docker, i added the following lines:
  auth_providers:
    - type: trusted_networks
      trusted_networks:
        - 172.16.0.0/12

and now it works again.

**Comment by evanjd** [comment]
Cheers.

I have pushed a commit to fix the broken error handler for next time.
