### ISSUE TITLE
legacy not working after 6 of april

### ISSUE THREAD

**Issue by divemasterjm** [evanjd/hass-logi-circle#6]
Hi, i've been using the legacy integration meanwhile i receive the api token, but after 6 months of requesting i didnt receive any mail from logitech, now is not working the legacy integration after april 6, can anyone help me?

**Comment by evanjd** [comment]
Hey @divemasterjm, it looks like Logitech are now only allowing requests from whitelisted user agents. This is fairly trivial to workaround, I'll have a fix up in the next few days.

**Comment by divemasterjm** [comment]
thanks i will aprecaite it!!!!
i have no response from them to get api token, therefore no way to have this camera online on HA.

**Comment by divemasterjm** [comment]
@evanjd did you found any workarround? 
thanks

**Comment by evanjd** [comment]
@divemasterjm Yep, had to spend some extra time getting [python-logi-circle](https://github.com/evanjd/python-logi-circle) building again, which I finished yesterday. Give me another day or so to get the integration updated.

**Comment by divemasterjm** [comment]
@evanjd thanks, if you need some tests just tell me

**Comment by evanjd** [comment]
@divemasterjm, I've just pushed an update which should hopefully resolve your problem.

Please note that I've deleted the `legacy` branch, and pushed everything to the `master` branch.

Let me know how you go.

**Comment by divemasterjm** [comment]
And how i install?

**Comment by evanjd** [comment]
Same process you would have followed when you first installed it. If you need a refresher refer to the [README](https://github.com/evanjd/hass-logi-circle/blob/master/README.md)

**Comment by divemasterjm** [comment]
apart from that, do i hace to change anything else? i saw directory name is different, do i have to change in configuratior.yaml logi_circle_legacy for logi_circle_master? do i have to rename directory or delete old one?

**Comment by divemasterjm** [comment]
it works!!!!
thanks so much!!!!
now i have my camera back

**Comment by evanjd** [comment]
Glad to hear it!
