### ISSUE TITLE
Logi Circle View Doorbell

### ISSUE THREAD

**Issue by Frederik-V** [evanjd/hass-logi-circle#8]
Dear.

Will this feature also work with the Logie Circle View Doorbell as well?
As this doorbell only works with Apple Homekit, I was wondering how to connect it with HA.

Looking forward for your answer(s).

Kindest regards,
Frederik

**Comment by evanjd** [comment]
Hi Frederik.

No, this HA integration (and the library that backs it) only supports Logi devices that use the Logi API. As the doorbell works exclusively with Apple HomeKit, this is not something this integration can access.
